# Generated by Django 5.0.3 on 2024-04-21 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0008_remove_order_order_taken_remove_order_order_taken_at'),
        ('ratings', '0002_ratingorder_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingorder',
            name='order_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_rating', to='freelance.orderrequest', verbose_name='Заказ'),
        ),
    ]
