# Generated by Django 5.0.3 on 2024-04-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0008_remove_order_order_taken_remove_order_order_taken_at'),
        ('ratings', '0003_alter_ratingorder_order_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to='freelance.userprofile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ratingorder',
            name='order_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_rating', to='freelance.order', verbose_name='Заказ'),
        ),
    ]
