# Generated by Django 5.0.3 on 2024-04-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_ratingorder_order_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingorder',
            name='order_request',
        ),
    ]
