# Generated by Django 5.0.3 on 2024-04-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0008_remove_order_order_taken_remove_order_order_taken_at'),
        ('ratings', '0007_remove_ratingorder_order_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingorder',
            unique_together={('order', 'user')},
        ),
    ]
