# Generated by Django 5.0.3 on 2024-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_alter_ratingorder_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingorder',
            unique_together=set(),
        ),
    ]
