# Generated by Django 5.0.3 on 2024-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0009_alter_userprofile_rating'),
        ('ratings', '0009_alter_ratingorder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingorder',
            name='order_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingorder',
            unique_together={('order', 'user')},
        ),
    ]
