# Generated by Django 5.0.3 on 2024-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0008_remove_order_order_taken_remove_order_order_taken_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Рейтинг'),
        ),
    ]
